# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexc" do
  name "vexc"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"
  version "1.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexc"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_amd64.tar.gz"
      sha256 "ba58ae45ccdf5ba7af5f4f2bfc1bce65bc0070b17578ad76764cd6f49a59f5b4"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_arm64.tar.gz"
      sha256 "3117239e7add64414975ef13e34aeea5af4fbfa1cf44c2d9fd32e271aa1d7686"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_amd64.tar.gz"
      sha256 "8b5236894438b0cd5a7ba0770d9b41839ae620b4582605adbfcbd8babc30a364"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_arm64.tar.gz"
      sha256 "5cd6fbaa57444349156d33e7b030661459196df1c15baf879d5f079d617725de"
    end
  end

  # No zap stanza required
end
